### ISSUE TITLE
repo is empty

### ISSUE THREAD

**Issue by oranhal** [serverlesspub/pizzeria-web-app#1]

**Comment by daryl-c** [comment]
+1

**Comment by mauricevancooten** [comment]
+1

**Comment by mloukianov** [comment]
+1

**Comment by brianyingling** [comment]
+1. The project in this book relies on this application in order to fully implement and test the examples in the authentication/authorization chapter.

**Comment by wigsaparelli** [comment]
I'm currently reading the book that requires this repo to complete the chapter 6 exercises - please put the code back!
