### ISSUE TITLE
identity pool facebook 

### ISSUE THREAD

**Issue by palashkantisen** [serverlesspub/pizzeria-web-app#3]
Hi, 

I've got this working and then: 
went to my user pool > App Client Settings > and enabled Facebook by providing "Facebook app ID", "App secret" and then "Authorize scope" as Email. 

then went to 
User Pool > Pizzaria > App Client Settings > and enabled Facebook 

But when I rerun npm run start, it does not show the Facebook option. 

So where are you overriding the Cognito setting? Or am I missing something? 

Thank you for your help. 

Regards, 
Palash. 
0220438919

**Comment by stojanovic** [comment]
Hi @palashkantisen,

This is just an example website, and we used default AWS Amplify login UI which unfortunately does not support Facebook button out of the box. If you want to add it in the frontend, you'll need to make a custom login page. You can see the instructions for customizing signup and login flows here: https://aws-amplify.github.io/docs/js/authentication.

Unfortunately, Facebook often changes their API, so it's possible that some parts of the book are affected with changes. Cognito part should work out-of-the-box, but Facebook chatbot part is probably slightly different now.

Let us know if we can help with anything.


Best regards,
Slobodan
